export const tabItems = [
	{
		id: 'monthly',
		title: 'Monthly',
		duration: 1,
	},
	{
		id: 'yearly',
		title: 'Yearly - Save 20%',
		duration: 12,
	},
];

export const packagesItems = [
	{
		id: '1',
		type: 'monthly',
		title: 'FREE',
		price: 0,
		active: true,
		details: [
			'500 unique visitors/month',
			'1 Website',
			'15 Days Storage',
			'1 Video bubble',
			'1 Button (Choose 1 button - Livechat, Call phone, Link to specific page, Built in Contact form, Book meeting on Calendly & Google)Brand customization',
		],
	},
	{
		id: '2',
		title: 'BUILD',
		type: 'monthly',
		price: 19,

		details: [
			'10,000 unique visitors/month',
			'1 Website',
			'30 Days Storage',
			'1 Videos',
			'Unlimited Buttons',
			'Brand customization',
		],
	},
	{
		id: '3',
		title: 'GROWTH',
		type: 'monthly',
		price: 25,
		details: [
			'40,000 unique visitors/month',
			'1 Website',
			'30 Days Storage',
			'5 Videos',
			'Unlimited Buttons',
			'Brand customization',
		],
	},
	{
		id: '4',
		title: 'EXPAND',
		type: 'monthly',
		price: 49,
		details: [
			'100,000 unique visitors/month',
			'1 Website',
			'90 Days Storage',
			'10 Videos',
			'Unlimited Buttons',
			'Brand customization',
		],
	},
	{
		id: '5',
		title: 'SCALE',
		type: 'monthly',
		price: 99,
		details: [
			'300,000 unique visitors/month',
			'1 Website',
			'90 Days Storage',
			'Unlimited Videos',
			'Unlimited Buttons',
			'Brand customization',
		],
	},
	{
		id: '6',
		title: 'FREE',
		type: 'yearly',
		active: true,
		price: 0,
		details: [
			'500 unique visitors/month',
			'1 Website',
			'15 Days Storage',
			'1 Video bubble',
			'1 Button (Choose 1 button - Livechat, Call phone, Link to specific page, Built in Contact form, Book meeting on Calendly & Google)Brand customization',
		],
	},
	{
		id: '7',
		title: 'BUILD',
		type: 'yearly',
		price: 15.83,
		details: [
			'10,000 unique visitors/month',
			'1 Website',
			'30 Days Storage',
			'1 Videos',
			'Unlimited Buttons',
			'Brand customization',
		],
	},
	{
		id: '8',
		title: 'GROWTH',
		type: 'yearly',
		price: 20.83,
		details: [
			'40,000 unique visitors/month',
			'1 Website',
			'30 Days Storage',
			'5 Videos',
			'Unlimited Buttons',
			'Brand customization',
		],
	},
	{
		id: '9',
		title: 'EXPAND',
		type: 'yearly',
		price: 40.83,
		details: [
			'100,000 unique visitors/month',
			'1 Website',
			'90 Days Storage',
			'10 Videos',
			'Unlimited Buttons',
			'Brand customization',
		],
	},
	{
		id: '10',
		title: 'SCALE',
		type: 'yearly',
		price: 82.5,
		details: [
			'300,000 unique visitors/month',
			'1 Website',
			'90 Days Storage',
			'Unlimited Videos',
			'Unlimited Buttons',
			'Brand customization',
		],
	},
];
